server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://db:5432/hatcher-db
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
