server:
  port: 8080

spring:
  application:
    name: hatcher-api
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: password
      initialization-mode: always
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: create
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:/db/migration
    out-of-order: false

security:
  jwt:
    token:
      secret-key: 8xATUx4r2L52
      expire-length: 604800000 #1 week

